# manifests/kong/fleet.yaml

# ------------------
# 新增的部分
# ------------------
# 为这个 Fleet Bundle 指定一个唯一的名称。
# 这个名称将用于被其他 Bundle 依赖 (dependsOn)。
name: "kong-operator-bundle"
# ------------------

# 目标：在所有纳管的集群中安装 Kong Gateway Operator
defaultNamespace: kong-system

# helm 定义了这是一个 Helm Chart 部署
helm:
  repo: "https://charts.konghq.com"
  chart: "kong"
  # 指定一个固定的 Chart 版本，这是最佳实践
  version: "2.16.0"
  # 如果命名空间不存在，则创建它
  createNamespace: true
  # Helm values 配置
  values:
    # Kong Gateway 配置
    Kong:
      enabled: true
      image:
        repository: kong/kong-gateway
        tag: "3.6.0"
      
      # 管理员 API 配置
      admin:
        enabled: true
        type: NodePort
        nodePort: 32001
      
      # 代理服务配置
      proxy:
        enabled: true
        type: NodePort
        http:
          nodePort: 32000
        https:
          nodePort: 32010
      
      # 数据库配置（使用 PostgreSQL）
      database: "off"
      
      # 声明式配置
      env:
        database: "off"
        role: "control_plane"
        cluster_cert: "/etc/secrets/kong-cluster-cert/tls.crt"
        cluster_cert_key: "/etc/secrets/kong-cluster-cert/tls.key"
        lua_package_path: "/opt/?.lua;;"
      
      # 运行时配置
      runMigrations: true
      
      # 资源限制（针对单节点环境）
    deployment:
      kong:
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
    
    # Ingress Controller 配置
    ingressController:
      enabled: true
      image:
        repository: kong/kubernetes-ingress-controller
        tag: "3.1.0"
      
      # 安装 CRDs (由应用 Bundle 安装)
      installCRDs: false
      
      # 资源限制
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    
    # PostgreSQL 配置（如果需要数据库模式）
    postgresql:
      enabled: false
    
    # 监控配置
    prometheus:
      enabled: false
    
    # 服务监控配置
    serviceMonitor:
      enabled: false