apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-test-config
  namespace: kong-apps
data:
  test-message: "Kong Gateway 部署测试"
  deployment-time: "{{ .Release.Time }}"
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-test-ingress
  namespace: kong-apps
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "true"
spec:
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: kong-test-service
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kong-test-service
  namespace: kong-apps
spec:
  selector:
    app: kong-test
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-test-deployment
  namespace: kong-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-test
  template:
    metadata:
      labels:
        app: kong-test
    spec:
      containers:
      - name: test-app
        image: nginx:alpine
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: test-config
          mountPath: /usr/share/nginx/html/config
      volumes:
      - name: test-config
        configMap:
          name: kong-test-config