# This is a minimal test file for debugging.
name: "test-pg-bundle-is-recognized-manifests"
defaultNamespace: "fleet-debug-test"

yaml:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: fleet-debug-cm2
  data:
    message: "Success! Fleet can see this file."